site_name: CAVE LLC
repo_url: https://github.com/gilt/cave/
pages:
- ['index.md', 'Introduction']
- ['deployment.md', 'Introduction', 'Deployment guide']
- ['architecture.md', 'Introduction', 'Architecture']
- ['getting-started.md', 'Introduction', 'Getting Started']
- ['alerts.md', 'Introduction', 'Primer on Alerts']
- ['grouping.md', 'Introduction', 'Date Grouping']
- ['metrics.md', 'Introduction', 'Primer on Metrics']
- ['tokens.md', 'Introduction', 'Primer on Tokens']
- ['api.md', 'API Guide', 'API Table of Contents']
- ['alerts/README.md', 'API Guide', 'Alerts - Table of Contents']
- ['alerts/create-org-alert.md', 'API Guide', 'Alerts - Create Organization Alert']
- ['alerts/get-org-alert.md', 'API Guide', 'Alerts - Get Organization Alert']
- ['alerts/get-org-alerts.md', 'API Guide', 'Alerts - List Organization Alerts']
- ['alerts/delete-org-alert.md', 'API Guide', 'Alerts - Delete Organization Alert']
- ['alerts/update-org-alert.md', 'API Guide', 'Alerts - Update Organization Alert']
- ['alerts/create-team-alert.md', 'API Guide', 'Alerts - Create Team Alert']
- ['alerts/delete-team-alert.md', 'API Guide', 'Alerts - Delete Team Alert']
- ['alerts/get-team-alert.md', 'API Guide', 'Alerts - Get Team Alert']
- ['alerts/get-team-alerts.md', 'API Guide', 'Alerts - List Team Alerts']
- ['alerts/update-team-alert.md', 'API Guide', 'Alerts - Update Team Alert']
- ['metrics/README.md', 'API Guide', 'Metrics - Table of Contents']
- ['metrics/get-org-metric-data.md', 'API Guide', 'Metrics - Get Organization Metrics']
- ['metrics/list-org-metrics.md', 'API Guide', 'Metrics - List Organization Metrics']
- ['metrics/publish-org-metrics.md', 'API Guide', 'Metrics - Publish Organization Metrics']
- ['metrics/get-team-metric-data.md', 'API Guide', 'Metrics - Get Team Metrics']
- ['metrics/list-team-metrics.md', 'API Guide', 'Metrics - List Team Metrics']
- ['metrics/publish-team-metrics.md', 'API Guide', 'Metrics - Publish Team Metrics']
- ['organizations/README.md', 'API Guide', 'Organizations - Table of Contents']
- ['organizations/create-org.md', 'API Guide', 'Organizations - Create Organization']
- ['organizations/get-org.md', 'API Guide', 'Organizations - Get Organization']
- ['organizations/update-org.md', 'API Guide', 'Organizations - Update Organization']
- ['organizations/delete-org.md', 'API Guide', 'Organizations - Delete Organization']
- ['organizations/get-org-users.md', 'API Guide', 'Organizations - Get Organization Users']
- ['organizations/add-org-user.md', 'API Guide', 'Organizations - Add Organization User']
- ['organizations/modify-org-user.md', 'API Guide', 'Organizations - Modify Organization User']
- ['organizations/remove-org-user.md', 'API Guide', 'Organizations - Remove Organization User']
- ['teams/README.md', 'API Guide', 'Teams - Table of Contents']
- ['teams/get-teams.md', 'API Guide', 'Teams - Get Organization Teams']
- ['teams/create-team.md', 'API Guide', 'Teams - Create Team']
- ['teams/get-team.md', 'API Guide', 'Teams - Get Team']
- ['teams/delete-team.md', 'API Guide', 'Teams - Delete Team']
- ['teams/get-team-users.md', 'API Guide', 'Teams - Get Team Users']
- ['teams/add-team-user.md', 'API Guide', 'Teams - Add Team User']
- ['teams/modify-team-user.md', 'API Guide', 'Teams - Modify Team User']
- ['teams/remove-team-user.md', 'API Guide', 'Teams - Remove Team User']
- ['tokens/README.md', 'API Guide', 'Tokens - Table of Contents']
- ['tokens/get-org-tokens.md', 'API Guide', 'Tokens - List Organization Tokens']
- ['tokens/create-org-token.md', 'API Guide', 'Tokens - Create Organization Token']
- ['tokens/get-org-token.md', 'API Guide', 'Tokens - Get Organization Token']
- ['tokens/delete-org-token.md', 'API Guide', 'Tokens - Delete Organization Token']
- ['tokens/get-team-tokens.md', 'API Guide', 'Tokens - List Team Tokens']
- ['tokens/create-team-token.md', 'API Guide', 'Tokens - Create Team Token']
- ['tokens/get-team-token.md', 'API Guide', 'Tokens - Get Team Token']
- ['tokens/delete-team-token.md', 'API Guide', 'Tokens - Delete Team Token']
- ['users/README.md', 'API Guide', 'Users - Table of Contents']
- ['users/register.md', 'API Guide', 'Users - Register User']
- ['users/confirm.md', 'API Guide', 'Users - Confirm User']
- ['users/login.md', 'API Guide', 'Users - Login User']
- ['users/forgot-password.md', 'API Guide', 'Users - Forgot Password']
- ['users/reset-password.md', 'API Guide', 'Users - Reset Password']
- ['users/get-info.md', 'API Guide', 'Users - Get User Information']
- ['users/patch-info.md', 'API Guide', 'Users - Update User Information']
- ['users/get-organizations.md', 'API Guide', 'Users - Get User Organizations']
- ['users/get-teams.md', 'API Guide', 'Users - Get User Teams']
